language: php

sudo: false

php:
  - 5.6

branches:
  only:
    - master

before_install:
  - composer install --prefer-dist --no-interaction

script: phpunit

notifications:
  mail: p.scheit@ps-webforge.com